export const reviews = [
  {
    carId: 1,
    user: "John Doe",
    rating: 5,
    comment:
      "Amazing car! Smooth ride and great performance. It handles very well on highways.",
    date: "2025-02-10",
    profession: "Software Engineer",
    location: "San Francisco, USA",
    helpfulVotes: 12,
  },
  {
    carId: 2,
    user: "Jane Smith",
    rating: 4,
    comment:
      "Great car, but could improve the fuel efficiency. Overall, the driving experience is good.",
    date: "2025-02-05",
    profession: "Product Manager",
    location: "New York, USA",
    helpfulVotes: 8,
  },
  {
    carId: 3,
    user: "Alex Brown",
    rating: 3,
    comment:
      "Good car overall, but the interior could use some upgrades. The infotainment system is a bit slow.",
    date: "2025-02-03",
    profession: "UX Designer",
    location: "London, UK",
    helpfulVotes: 3,
  },
  {
    carId: 4,
    user: "Emily White",
    rating: 4,
    comment:
      "Great value for the price. Would recommend for anyone looking for an affordable and reliable car.",
    date: "2025-02-02",
    profession: "Marketing Specialist",
    location: "Sydney, Australia",
    helpfulVotes: 5,
  },
  {
    carId: 5,
    user: "David Green",
    rating: 5,
    comment:
      "Best car I’ve ever driven! Worth every penny. The performance is top-notch, and it's extremely comfortable.",
    date: "2025-01-28",
    profession: "Business Owner",
    location: "Toronto, Canada",
    helpfulVotes: 15,
  },
];

export const cars = [
  {
    id: 1,
    brand: "Toyota",
    fuel: 50,
    seats: 5,
    price: 30000,
    gasoline: "Gasoline",
    steering: "Power Steering",
    capacity: "2.0L",
    type: "Sedan",
    description:
      "Toyota’s legacy of reliability meets cutting-edge technology in this robust vehicle. Perfect for every journey, from city roads to rugged terrain.",
  },
  {
    id: 2,
    brand: "Honda",
    fuel: 45,
    seats: 5,
    price: 28000,
    gasoline: "Gasoline",
    steering: "Electric Steering",
    capacity: "1.8L",
    type: "SUV",
    description:
      "With unmatched efficiency and sleek design, Honda combines practicality with style, making every drive a smooth and exhilarating experience.",
  },
  {
    id: 3,
    brand: "BMW",
    fuel: 60,
    seats: 4,
    price: 50000,
    gasoline: "Premium Gasoline",
    steering: "Electric Steering",
    capacity: "3.0L",
    type: "Coupe",
    description:
      "BMW’s engineering excellence is embodied in this high-performance beauty, designed to deliver power and precision on every twist and turn.",
  },
  {
    id: 4,
    brand: "Audi",
    fuel: 55,
    seats: 4,
    price: 45000,
    gasoline: "Gasoline",
    steering: "Power Steering",
    capacity: "2.5L",
    type: "Sedan",
    description:
      "Audi redefines sophistication and comfort. This sleek design is a perfect harmony of luxury, performance, and innovation.",
  },
  {
    id: 5,
    brand: "Mercedes",
    fuel: 70,
    seats: 5,
    price: 60000,
    gasoline: "Premium Gasoline",
    steering: "Electric Steering",
    capacity: "3.5L",
    type: "Luxury SUV",
    description:
      "Mercedes-Benz continues to push the limits of luxury with a stunning vehicle that blends cutting-edge technology with timeless elegance.",
  },
  {
    id: 6,
    brand: "Ford",
    fuel: 50,
    seats: 5,
    price: 25000,
    gasoline: "Gasoline",
    steering: "Power Steering",
    capacity: "2.0L",
    type: "Sedan",
    description:
      "Ford brings together durability and performance in this all-around vehicle, perfect for family trips and city driving alike.",
  },
  {
    id: 7,
    brand: "Chevrolet",
    fuel: 65,
    seats: 5,
    price: 32000,
    gasoline: "Gasoline",
    steering: "Power Steering",
    capacity: "2.5L",
    type: "SUV",
    description:
      "Chevrolet combines rugged power with a refined design, creating a comfortable ride for both off-road and urban adventures.",
  },
  {
    id: 8,
    brand: "Nissan",
    fuel: 55,
    seats: 5,
    price: 28000,
    gasoline: "Gasoline",
    steering: "Electric Steering",
    capacity: "2.2L",
    type: "SUV",
    description:
      "Nissan’s balance of power and economy makes this SUV an excellent choice for those seeking both efficiency and versatility.",
  },
  {
    id: 9,
    brand: "Tesla",
    fuel: 0,
    seats: 5,
    price: 70000,
    gasoline: "Electric",
    steering: "Electric Steering",
    capacity: "Electric",
    type: "Electric Sedan",
    description:
      "Tesla’s groundbreaking electric vehicle technology delivers both performance and sustainability in this cutting-edge ride.",
  },
  {
    id: 10,
    brand: "Hyundai",
    fuel: 45,
    seats: 5,
    price: 27000,
    gasoline: "Gasoline",
    steering: "Power Steering",
    capacity: "1.8L",
    type: "Sedan",
    description:
      "Hyundai offers a combination of affordability and advanced features, making it an ideal option for budget-conscious drivers.",
  },
  {
    id: 11,
    brand: "Tesla",
    fuel: 5,
    seats: 5,
    price: 23000,
    gasoline: "Electric",
    steering: "Electric Steering",
    capacity: "Electric",
    type: "Electric Sedan",
    description:
      "The Tesla experience now comes at an even more affordable price, with all the electric efficiency and innovation you expect.",
  },
  {
    id: 12,
    brand: "Chevrolet",
    fuel: 52,
    seats: 6,
    price: 77000,
    gasoline: "Gasoline",
    steering: "Power Steering",
    capacity: "3.0L",
    type: "Luxury SUV",
    description:
      "Chevrolet’s high-end SUV brings luxury and performance together in one package, perfect for both comfort and adventure.",
  },
];
